### ISSUE TITLE
Initial Roadmap

### ISSUE THREAD

**Issue by mizdra** [mizdra/graphql-codegen-typescript-fabbrica#1]
## v0.1.0 (MVP)
- [x] #2
- [x] Various field resolvers
  - #3
  - #10
  - #29
- [x] Sequence
  - [x] #4
  - [x] #5
- [x] #9 
- [x] #12
- [x] #19 
- [x] #22
- [x] #23
- [x] #27
- [x] #28 

## v0.2.0
- [x] Improve GraphQL compatibility (https://github.com/mizdra/graphql-fabbrica/pull/34)
  - [x] Enum
  - [x] Union
  - [x] Input (#37)
  - [x] Interface
  - [x] Custom Scalar
- [x] Improve graphql-code-generator compatibility 
  - [x] Change type name (#35)
  - [x] Description comment (#38)
- [x] Improve relay compatibility
  - [x] https://github.com/mizdra/graphql-fabbrica/pull/43
- [x] https://github.com/mizdra/graphql-fabbrica/pull/45

## v0.3.0
- [x] https://github.com/mizdra/graphql-codegen-typescript-fabbrica/pull/47
- [x] https://github.com/mizdra/graphql-codegen-typescript-fabbrica/pull/49

**Comment by mizdra** [comment]
The initial roadmap is complete.
